Repository woowa-techcamp-2020/market-3, pull requests merged in 2020-07, with the labels that each got.

#32 [layout] 로그인 페이지의 마크업을 개선하라
  public/css/main.css
  public/css/signIn.css
  public/css/signUp.css
  public/css/signUpSuccess.css
  public/img/banner.png
  public/js/main.js
  public/js/signUp.js
  static/css/signIn.css
  views/main.pug
  views/signIn.pug
  views/signUp.pug
  views/signUpSuccess.pug
  views/temp.pug
Labels: FE, enhancement

#36 [layout] 회원가입 페이지 마크업을 개선하라
  public/css/signUp.css
  views/signUp.pug
Labels: FE, enhancement

#35 [layout] 메인 페이지의 마크업을 개선하라
  public/css/main.css
  views/main.pug
Labels: FE, enhancement

#39 [layout] 회원가입 성공 페이지의 스타일을 개선하라
  public/css/signUpSuccess.css
  views/signUpSuccess.pug
Labels: FE, enhancement

#41 [feature] 비밀번호 입력창을 구현하라
  public/css/signUp.css
  public/js/signUp.js
  public/js/utils/domControl.js
  public/js/utils/inputHandlers.js
  public/js/utils/validations.js
  views/signUp.pug
Labels: FE, new implementation

#42 [feature] 사용자 암호를 암호화하라
  api/login.js
  app.js
  controllers/authController.js
  controllers/userController.js
  database/db.js
  database/userSchema.js
  package-lock.json
  package.json
  routes/api.js
  routes/auth.js
  routes/index.js
  routes/user.js
  services/authService.js
  services/userService.js
  test/api/logIn.test.js
  test/services/authService.test.js
Labels: BE, enhancement

#47 [feature] 로그아웃 기능을 구현하라
  controllers/authController.js
  public/js/main.js
  public/js/utils/cookie.js
  views/main.pug
  views/signIn.pug
Labels: BE

#48 [layout] pug 페이지들을 연결하라
  controllers/authController.js
  controllers/userController.js
  public/css/main.css
  public/css/signUp.css
  public/js/main.js
  public/js/signIn.js
  public/js/signUpSuccess.js
  public/js/utils/cookie.js
  views/main.pug
  views/signIn.pug
  views/signUp.pug
  views/signUpSuccess.pug
Labels: BE, FE, enhancement

#49 [feature] 이름 입력창을 구현하라
  public/js/signUp.js
  public/js/utils/inputHandlers.js
  public/js/utils/validations.js
Labels: FE, new implementation

#59 [feature] 회원가입 페이지 가입완료 버튼을 구현하라
  controllers/userController.js
  database/userSchema.js
  services/userService.js
  views/signUp.pug
Labels: BE, new implementation

#61 [feature] 로그인 화면의 아이디 입력 오류 확인 기능을 구현하라
  public/css/signIn.css
  public/js/main.js
  public/js/signIn.js
  public/js/signUp.js
  public/js/utils/cookie.js
  public/js/utils/domControl.js
  public/js/utils/inputHandlers.js
  public/js/utils/validations.js
  views/main.pug
  views/signIn.pug
  views/signUp.pug
Labels: FE, new implementation

#64 [hotfix] 회원가입페이지의 휴대폰 인증 버튼 버그 수정
  public/js/signUp.js
  public/js/utils/inputHandlers.js
Labels: bug, hot-fix

#65 [hotfix] 회원가입페이지의 가입완료 유효성 검사 버그 수정
  public/js/signUp.js
  public/js/utils/inputHandlers.js
Labels: bug, hot-fix
